services:
  - type: web
    name: drawing-pad-frontend
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_SOCKET_URL
        value: https://drawing-pad-backend.onrender.com

  - type: web
    name: drawing-pad-backend
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: ORIGIN
        value: https://drawing-pad-frontend.onrender.com
